### ISSUE TITLE
Decompress fails on KeyError in the dictionary.

### ISSUE THREAD

**Issue by MosheWorld** [DyakoVlad/python-LZ78#1]
The trace is:
Traceback (most recent call last):
  File "c:/Users/mmosh/Desktop/Compression Project/python-LZ78/LZ78.py", line 47, in <module>
    decodeLZ('encoded.txt', 'decoded.txt')
  File "c:/Users/mmosh/Desktop/Compression Project/python-LZ78/LZ78.py", line 38, in decodeLZ
    dict_of_codes[str(code)] = dict_of_codes[combination] + char
KeyError: '5172720170107090248506'

I am running huge text and it fails on that KeyError, what could cause the problem in the trace?

**Comment by MosheWorld** [comment]
The author doesn't respond.
